In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [22]:
script_dir = os.path.dirname(os.path.abspath(os.getcwd()))
file_path = os.path.join(script_dir, "raw_datasets", "earthquake.xlsx")
df = pd.read_excel(file_path)

In [5]:
df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,2000-0023-BGD,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp0009khm,NaN,BGD,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm2_code"":5772,""adm2_name"":""Cox's Bazar""}]",2011-04-07,2023-09-25
1,2000-0033-CHN,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp0009m4u,NaN,CHN,...,NaN,NaN,NaN,NaN,73500.0,130056.0,56.514291,"[{""adm2_code"":13307,""adm2_name"":""Chuxiong Yi""}...",2003-09-09,2023-09-25
2,2000-0036-CHN,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp0009mq6,NaN,CHN,...,NaN,NaN,NaN,NaN,483.0,855.0,56.514291,"[{""adm2_code"":13308,""adm2_name"":""Honghe Hani a...",2010-03-04,2023-09-25
3,2000-0041-CHN,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp0009m1j,NaN,CHN,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm2_code"":13179,""adm2_name"":""Anshan""}]",2003-09-09,2023-09-25
4,2000-0051-IRN,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp0009mz6,NaN,IRN,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm2_code"":40901,""adm2_name"":""Bardeskan""},{...",2014-03-07,2023-09-25

In [7]:
df.rename(columns={df.columns[0]: 'Year'}, inplace=True)

In [8]:
required_columns = ['Year', 'Disaster Type', 'Country', 'Location', 'Total Affected', 'Magnitude']
df = df[required_columns]

In [9]:
df.isnull().sum()

Year               0
Disaster Type      0
Country            0
Location           5
Total Affected    20
Magnitude          2
dtype: int64

In [13]:
df['Location'].fillna(df['Location'].mode()[0], inplace=True)
df['Total Affected'].fillna(df['Total Affected'].mode()[0], inplace=True)
df['Magnitude'].fillna(df['Magnitude'].mode()[0], inplace=True)

/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_58556/77384327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Location'].fillna(df['Location'].mode()[0], inplace=True)
/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_58556/77384327.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total Affected'].fillna(df['Total Affected'].mode()[0], inplace=True)
/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_58556/77384327.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total Affected'].fillna(df['Total Affected'].mode()[0], inplace=True)
/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_58556/77384327.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Magnitude'].fillna(df['Magnitude'].mode()[0], inplace=True)
/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_58556/77384327.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Magnitude'].fillna(df['Magnitude'].mode()[0], inplace=True)

In [14]:
df.isnull().sum()

Year              0
Disaster Type     0
Country           0
Location          0
Total Affected    0
Magnitude         0
dtype: int64

In [15]:
df

,Year,Disaster Type,Country,Location,Total Affected,Magnitude
0,2000-0023-BGD,Earthquake,Bangladesh,"Maheshkhali area (Cox's Bazar district, Chitta...",1000.0,4.3
1,2000-0033-CHN,Earthquake,China,"Yongren Xian, Yao'an Xian, Nanhua Xian, Dayao ...",1855007.0,5.9
2,2000-0036-CHN,Earthquake,China,"Mile Xian area (Honghe Hani and Yi district, Y...",10302.0,4.9
3,2000-0041-CHN,Earthquake,China,"Xiuyan Manzu Zizhixian area (Anshan district, ...",62030.0,5.1
4,2000-0051-IRN,Earthquake,Iran (Islamic Republic of),"Kashmar, Bardeskan districts (Khorasan)",2015.0,5.3
...,...,...,...,...,...,...
662,2024-0848-CUB,Earthquake,Cuba,"BartolomÃ© MasÃ³, PilÃ³n and Niquero municipaliti...",6007.0,6.8
663,2024-0911-VUT,Earthquake,Vanuatu,"Ludian Xian area (Zhaotong district, Yunnan Sh...",80265.0,7.3
664,2025-0004-CHN,Earthquake,China,"Xizang, Tibet Autonomous Region",46688.0,7.1
665,2025-0004-NPL,Earthquake,Nepal,"Ludian Xian area (Zhaotong district, Yunnan Sh...",83.0,7.1
666,2025-0018-ETH,Earthquake,Ethiopia,"Southern Afar, northern Oromia, Amhara regions",99000.0,5.2

In [18]:
df['Year'] = df['Year'].astype(str).str[:4]
df['Location'] = df['Location'].str.split(',').str[0]

/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_58556/4287316212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Year'].astype(str).str[:4]
/var/folders/0p/vdvp33851vn1jcfb8t3_kyzm0000gn/T/ipykernel_58556/4287316212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Location'] = df['Location'].str.split(',').str[0]

In [19]:
df

,Year,Disaster Type,Country,Location,Total Affected,Magnitude
0,2000,Earthquake,Bangladesh,Maheshkhali area (Cox's Bazar district,1000.0,4.3
1,2000,Earthquake,China,Yongren Xian,1855007.0,5.9
2,2000,Earthquake,China,Mile Xian area (Honghe Hani and Yi district,10302.0,4.9
3,2000,Earthquake,China,Xiuyan Manzu Zizhixian area (Anshan district,62030.0,5.1
4,2000,Earthquake,Iran (Islamic Republic of),Kashmar,2015.0,5.3
...,...,...,...,...,...,...
662,2024,Earthquake,Cuba,BartolomÃ© MasÃ³,6007.0,6.8
663,2024,Earthquake,Vanuatu,Ludian Xian area (Zhaotong district,80265.0,7.3
664,2025,Earthquake,China,Xizang,46688.0,7.1
665,2025,Earthquake,Nepal,Ludian Xian area (Zhaotong district,83.0,7.1
666,2025,Earthquake,Ethiopia,Southern Afar,99000.0,5.2

In [20]:
df.to_csv("earthquake_cleaned.csv", index=False)

In [21]:
df.isnull().sum()

Year              0
Disaster Type     0
Country           0
Location          0
Total Affected    0
Magnitude         0
dtype: int64